In [4]:
import pandas as pd
import rasterio
from geollm_scripts.geollm_utils import *
import re
from geollm_scripts.make_predictions_and_visualize import run_task_for_data

path_raster = "data/geollm/ppp_2020_1km_Aggregated.tif"
path_prompts = "data/geollm/world_prompts.jsonl"

In [26]:
def extract_coord_from_line(text):
    pattern = r'Coordinates:\s*\((-?\d+\.\d+),\s*(-?\d+\.\d+)\)'

    match = re.search(pattern, text)
    if match:
        lon = float(match.group(1))
        lat = float(match.group(2))
    
    return lon, lat

def get_density_at(src, lon, lat):
    return list(src.sample([(lon, lat)]))[0][0]

def get_coord_from_json(json_file, line_range=(0, 10)):
    prompts = []
    lons = []
    lats = []
    df_json = pd.read_json(json_file, lines=True)
    for i in range(*line_range):
        prompt = df_json.iloc[i]['text']
        lon, lat = get_coordinates(prompt)

        prompts.append(prompt)
        lons.append(lon)
        lats.append(lat)
    
    df_ret = pd.DataFrame({"prompt" : prompts, "lon": lons, "lat" : lats})
    return df_ret

def add_population_density(df, tif_path, lon_col="lon", lat_col="lat"):

    coords = list(zip(df[lon_col], df[lat_col]))

    groundtruth = [extract_data(lat, lon, tif_path) for lat, lon in coords]

    df = df.copy()
    df["population"] = groundtruth

    return df

In [27]:
df = get_coord_from_json(path_prompts, line_range=(0,2000))
print(df.shape)
df.head()

(2000, 3)

                                              prompt       lon        lat
0  Coordinates: (-5.87958, 14.98625)\n\nAddress: ...  -5.87958   14.98625
1  Coordinates: (67.29542, 14.72792)\n\nAddress: ...  67.29542   14.72792
2  Coordinates: (58.37875, -134.63042)\n\nAddress...  58.37875 -134.63042
3  Coordinates: (55.05375, 58.97792)\n\nAddress: ...  55.05375   58.97792
4  Coordinates: (53.18708, 8.23625)\n\nAddress: "...  53.18708    8.23625

In [28]:
df = add_population_density(df, path_raster)
print(df.shape)
df.head()

(2000, 4)

,prompt,lon,lat,population
0,"Coordinates: (-5.87958, 14.98625)\n\nAddress: ...",-5.87958,14.98625,44509.261719
1,"Coordinates: (67.29542, 14.72792)\n\nAddress: ...",67.29542,14.72792,11661.978516
2,"Coordinates: (58.37875, -134.63042)\n\nAddress...",58.37875,-134.63042,17762.666016
3,"Coordinates: (55.05375, 58.97792)\n\nAddress: ...",55.05375,58.97792,33767.539062
4,"Coordinates: (53.18708, 8.23625)\n\nAddress: ""...",53.18708,8.23625,193455.515625

In [2]:
model_name = "HuggingFaceTB/SmolLM3-3B"
device = "cuda"
api = "local"
prompt_file_path = "data/geollm/world_prompts.jsonl"
less_path = "data/geollm/small_world_prompts.jsonl"
task = "Population Density"

In [3]:

run_task_for_data(model_api=api, model=model_name, task=task, prompt_file_path=less_path, api_key=device)

 >> Loading local model <<

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

PROMPT 1:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (-5.87958, 14.98625)

Address: "Uíge, Angola"

Nearby Places:
"
3.4 km North-East: Kimbala
4.7 km North-East: Kimpangu
4.8 km North-East: Kimvindu
5.9 km North-East: Kikongo
15.7 km North-West: Tunda
15.9 km North-East: Kungu Lusanga
17.5 km North: Luzanga
18.2 km North: Mbanza Ngombe
18.4 km North-West: Wene
18.6 km North-West: Kongo Dia Kati
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 1.5.

RATING: 1.5

PROMPT 2:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (67.29542, 14.72792)

Address: "Tverlandsveien, Løding, Engmoen, Løding, Bodø, Nordland, Norge"

Nearby Places:
"
0.2 km South: Engmoen
0.3 km South-West: Fitjan
0.3 km North: Vestre Løding
0.5 km North-East: Haug
0.6 km East: Sørgjerdet
0.6 km South: Oddan
0.8 km East: Løding
1.0 km South-West: Oddsjøen
1.1 km North-East: Kringla
1.1 km North-East: Østre Løding
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 1.7

RATING: 1.7

PROMPT 3:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (58.37875, -134.63042)

Address: "Glacier Highway, Juneau, Alaska, United States"

Nearby Places:
"
1.6 km North-West: Auke Bay
4.0 km East: Mendenhaven
4.0 km East: Mendenhall Valley
4.3 km West: Fairhaven
7.2 km West: Lena Beach
8.0 km East: Lemon Creek
8.4 km North-West: Tee Harbor
8.9 km South-East: Vanderbilt Hill
11.9 km North-East: Suicide Basin
13.6 km North-West: Saint Terese
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 9.7.

RATING: 9.7

PROMPT 4:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (55.05375, 58.97792)

Address: "Кольцевая улица, Первомайский поселок, Саткинское городское поселение, Саткинский район, Челябинская область, Уральский федеральный округ, Россия"

Nearby Places:
"
1.7 km South-West: Первомайский поселок
2.6 km West: Тёплый посёлок
3.0 km South: Малая Запань
3.5 km South-East: площадь 1 Мая
3.5 km South-East: Сатка
3.6 km West: Западный микрорайон
4.0 km South-East: Козий остров
5.2 km North: Речная
6.6 km South-East: Лесничество
8.0 km East: Большая Запань
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 2.8.

RATING: 2.8

PROMPT 5:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (53.18708, 8.23625)

Address: "Schmaler Weg, Etzhorn, Oldenburg, Niedersachsen, Deutschland"

Nearby Places:
"
0.2 km South-East: Etzhorn
1.1 km South: Haseln
1.5 km South: Hoheheide
1.7 km South: Schellstede
1.8 km South-East: Kummerkamp
1.9 km North-East: Wahnbeker Büsche
2.0 km East: Göllen
2.1 km North-East: Hogeland
2.1 km South-East: Dornstede
2.1 km North: Wahnbek
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 2.3.

RATING: 2.3

PROMPT 6:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (46.28708, -96.61375)

Address: "Harrison Road, Wahpeton, Richland County, North Dakota, United States"

Nearby Places:
"
2.4 km South: Wahpeton
3.5 km South-East: Breckenridge
9.4 km North: Brushvale
9.8 km West: Dwight
10.2 km South: Elmore
10.8 km West: Farmington
12.7 km East: Wilkin
15.3 km South-East: Doran
15.3 km South: Tyler
16.0 km East: Everdell
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 4.8.

RATING: 4.8

PROMPT 7:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (45.83708, 130.85292)

Address: "新城街道, 新兴区, 七台河市, 黑龙江省, 中国"

Nearby Places:
"
1.5 km South: 新城街道
2.7 km South-East: 新兴区
3.8 km North: 长兴乡
3.8 km North-West: 中鲜村
3.8 km South-East: 新建街道
4.1 km South-West: 缸窑沟街道
4.4 km South-East: 红旗镇
4.7 km South: 新合街道
4.8 km South-East: 兴华街道
5.2 km East: 欣源街道
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 2.1

RATING: 2.1

PROMPT 8:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (8.58708, -74.23875)

Address: "Tiquisio, Tiquisio, Mojana, Bolívar, Colombia"

Nearby Places:
"
4.4 km South-West: Tiquisio
5.2 km West: COLORADO
6.9 km North-East: EL SUDAN
10.0 km West: Botija
10.9 km North: Santa Lucía
12.3 km North: LA RUFINA
12.6 km North: RUFINA NUEVA
12.7 km North-East: Nueva Delhi
13.9 km South-West: TIQUISIO NUEVO
14.0 km South-West: PUERTO COCA
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 2.5.

RATING: 2.5

PROMPT 9:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (55.34542, 86.14458)

Address: "проспект Ленина, Центральный район, Кемерово, Кемеровский городской округ, Кемеровская область, Сибирский федеральный округ, Россия"

Nearby Places:
"
2.2 km North-East: Шалготарьян
2.6 km South-West: ФПК
3.2 km North-West: Красная
3.8 km West: Кемерово
4.1 km West: Геологоразведка
4.3 km East: Сухово
4.4 km West: Швейка
4.6 km North: СНТ «Труженик»
4.6 km South-East: Металлплощадка
5.4 km South-West: Южный
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 7.8

RATING: 7.8

PROMPT 10:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (39.75375, -7.93042)

Address: "Rua Doutor António Valente, Proença-a-Nova, Proença a Nova e Peral, Proença-a-Nova, Castelo Branco, Portugal"

Nearby Places:
"
0.6 km South-East: Proença-a-Nova
1.1 km North: Sarzedinha
1.5 km North-East: Braçal
1.7 km South-West: Casal Velho
1.8 km South: Labrunhal Cimeiro
2.0 km North-West: Eiras
2.3 km East: Amoreira
2.3 km South: Labrunhal Fundeiro
2.6 km South: Galisteu Cimeiro
2.7 km South-East: Galisteu Fundeiro
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 9.9

RATING: 9.9

PROMPT 11:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (8.72042, -75.88042)

Address: "Comuna 4, Perímetro Urbano Montería, Centro, Córdoba, Colombia"

Nearby Places:
"
1.4 km South-West: El Prado
2.8 km South: Bajo Las Palmeras
3.0 km North-West: Granja Nacional Batallon
3.2 km North-West: Cartagena
3.4 km North: Montería
3.9 km South-East: LOMAGRANDE
4.1 km South: LA MANSIÓN
4.3 km South: ALEMANIA
4.4 km North: Urb. Villa Campestre
4.4 km East: EL PURGATORIO
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 1.5

RATING: 1.5

PROMPT 12:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (11.58708, 37.38625)

Address: "B31, Sebatamit, West Gojjam, አማራ ክልል / Amhara, ኢትዮጵያ"

Nearby Places:
"
0.9 km North: ባሕር-ዳር /Bahir Dar
1.5 km North: Bahrdar Giyorgis
1.6 km East: ሳር መንደር
2.6 km North-East: ሻምቡ አካባቢ
3.3 km North: Debra Maryam
3.6 km North-East: Abba
6.2 km South: Sebatamit
7.2 km North-East: Gheddera
7.4 km North-West: Dek'E
7.5 km North: Kibran
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 3.5

RATING: 3.5

PROMPT 13:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (43.68708, 51.23625)

Address: "2-й квартал, Басқұдық, Ақтау, Мунайлинский район - Мұнайлы ауданы, Маңғыстау облысы, Қазақстан"

Nearby Places:
"
2.2 km West: Басқұдық
3.5 km South-West: Атамекен
3.9 km East: Мангистау-3 мкр.
3.9 km West: Шыгыс-3 мкр.
4.0 km West: Шығыс-2 шағын ауданы
4.1 km West: Шығыс-1 шағын ауданы
4.6 km West: 31А шағын ауданы
4.7 km North-East: Мангистау-5 мкр.
4.8 km South-West: 29А шағын ауданы
4.8 km West: 32Б мкр.
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 1.0

RATING: 1.0

PROMPT 14:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (3.60375, 98.66958)

Address: "Speedline Auto, Jalan Haji Adam Malik, Kesawan, Medan Barat, Kota Medan, Sumatera Utara, Indonesia"

Nearby Places:
"
0.3 km North-East: Silalas
0.8 km North-West: Sei Agul
0.9 km South: Sekip
1.0 km South-West: Sei Putih Timur I
1.4 km North-East: Glugur Darat II
1.4 km South: Petisah Tengah
1.6 km South-West: Sei Putih Timur Ii
1.6 km East: Pandau Hilir
1.6 km South: Petisah
1.6 km South: Medan
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 4.3

RATING: 4.3

PROMPT 15:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (51.24542, 58.59458)

Address: "Никельская улица, Первомайский, Ленинский район, Орск, городской округ Орск, Оренбургская область, Приволжский федеральный округ, Россия"

Nearby Places:
"
1.4 km North-East: Первомайский
2.1 km South: Старокирпичный
2.6 km West: Никель
3.0 km East: Зелёная долина
3.6 km East: ОЗТП
3.8 km South-East: Кумакские высоты
3.9 km South-East: Железнодорожный
4.1 km South: Вокзальный
4.8 km South: 6-й микрорайон
5.0 km West: Строителей
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 0.9.

RATING: 0.9

PROMPT 16:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (30.86208, 61.73625)

Address: "لال خان, بخش مرکزی زهک, شهرستان زهک, استان سیستان و بلوچستان, ایران"

Nearby Places:
"
0.3 km East: لال خان
0.8 km North-West: جی سرخ علیا
1.0 km East: خواجه احمد
1.3 km North-East: ده غفور
1.6 km South: شهرک کوهک
2.0 km North: ده احمدعلیخان
2.4 km South-East: امیرنظام
2.5 km North: عبدالعزیز
2.5 km South: جی سرخ سفلی
2.8 km North: ده نو
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 2.4

RATING: 2.4

PROMPT 17:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (47.24542, 39.69458)

Address: "улица Нансена, Рабочий городок, Октябрьский район, Ростов-на-Дону, городской округ Ростов-на-Дону, Ростовская область, Южный федеральный округ, Россия"

Nearby Places:
"
0.6 km North: площадь Народного Ополчения
0.7 km North-West: Безымянная Балка
0.9 km South-East: Рабочий городок
1.2 km North: Новый город
1.7 km South: Новое Поселение
1.7 km South-West: Первомайский посёлок
2.0 km East: Трамвайщик
2.5 km West: СТ "ППЖ Ж1", бывший СТ "Нефтяник"
2.6 km North-West: Каменка
2.7 km North-East: Северный посёлок
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 3.7

RATING: 3.7

PROMPT 18:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (29.35375, 48.01125)

Address: "الإمام مالك, شارع جر ير, قطعة 3, الدعية, مدينة الكويت, العاصمة, الكويت"

Nearby Places:
"
0.4 km North: الدعية
1.0 km South-West: القادسية
1.3 km East: الشعب
1.7 km North-West: الدسمة
1.8 km West: المنصوريَّة
2.1 km South-East: حولي
2.3 km North: بنيد القار
2.3 km South-West: النزهة
2.9 km West: ضاحية عبدالله السالم
3.0 km South-West: الروضة
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 9.8

RATING: 9.8

PROMPT 19:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (54.94542, 43.36958)

Address: "Кремешки, Саров, городской округ Саров, Нижегородская область, Приволжский федеральный округ, Россия"

Nearby Places:
"
2.5 km South-West: Саров
3.7 km South-East: Кордон Новеньковский
6.4 km West: Новостройка
6.5 km North: Кременки
6.6 km West: Хвощёво
7.0 km West: Цыгановка
7.4 km North: Рузаново
8.4 km West: Орешки
8.5 km West: Полевой
9.0 km North-West: Яковлевка
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 3.7.

RATING: 3.7

PROMPT 20:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (-39.02125, -67.56375)

Address: "Alfredo Palacios, Norte, Norte, SUPE, General Roca, Municipio de General Roca, Departamento General Roca, Río Negro, Argentina"

Nearby Places:
"
0.0 km South-West: 36 Viviendas
0.1 km South: Don Fernando
0.2 km South-West: Fernando Rajneri
0.2 km East: 122 Viviendas
0.4 km North-East: 500 Viviendas
0.4 km East: 118 Viviendas
0.5 km North-East: 122 Viviendas
0.5 km West: Norte
0.5 km South: Frank
0.6 km West: Norte
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 1.2

RATING: 1.2

PROMPT 21:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (0.54542, 123.06125)

Address: "Gorontalo, Gorontalo, Indonesia"

Nearby Places:
"
0.8 km South: Gorontalo
2.3 km South-East: Molosipat W
3.1 km South: Talumolo
3.1 km South: Tenda
3.2 km North-West: Huangobotu
3.3 km West: Buladu
4.0 km North-West: Tuladenggi
4.2 km West: Dulomo
4.4 km South: Batato
4.4 km North: Tomulabutao
"

Population Density (On a Scale from 0.0 to 9.9):

COMPLETION: <think>

</think>
My answer is 2.3.

RATING: 2.3

PROMPT 22:

You will be given data about a specific location randomly sampled from all human-populated locations on Earth.
You give your rating keeping in mind that it is relative to all other human-populated locations on Earth (from all continents, countries, etc.).
You provide ONLY your answer in the exact format "My answer is X.X." where 'X.X' represents your rating for the given topic.


Coordinates: (-3.27958, 37.58625)

Address: "Mwika, Moshi Rural, Kilimanjaro, Northern Zone, Tanzania"

Nearby Places:
"
0.7 km West: Mwika

In [2]:
from geollm_scripts.calculate_spearman_correlation import calculate_spearman_correlation
import pandas as pd

def print_spearman_correl(predictions_csv, groundtruth_tif):
    df = pd.read_csv(predictions_csv)
    if 'Latitude' in df.columns and 'Longitude' in df.columns and 'Predictions' in df.columns:
        coordinates = list(zip(df['Latitude'], df['Longitude']))
        predictions = df['Predictions']
    else:
        raise ValueError("CSV file must contain 'Latitude', 'Longitude', and 'Predictions' columns.")

    corr = calculate_spearman_correlation(coordinates, predictions, groundtruth_tif)

    print(f"Spearman correlation: {corr:.2f}")

In [3]:
predictions_csv = "results/HuggingFaceTB_SmolLM3_3B_Population_Density_small_world_prompts.csv"
groundtruth_tif = "data/geollm/ppp_2020_1km_Aggregated.tif"

print_spearman_correl(predictions_csv, groundtruth_tif)

Spearman correlation: 0.22

## GeoLLM sur les couches cachés